// Code generated by flinch-cli. DO NOT EDIT.
package data

import (
	"embed"
	"github.com/adm87/flinch/engine/resources"
)

// =============== Embedded Directories ===============

//go:embed static
var staticEmbeddedFS embed.FS

// =============== Assets ===============

const (
	CharactersData          resources.Asset = 0xfca5063c33d5d3f6 // assets/aseprite/characters/characters_data.json
	CharactersImg           resources.Asset = 0x17d0b26b6cf1aecc // assets/aseprite/characters/characters_img.png
	TilemapExampleA         resources.Asset = 0x7d30d7ac63574117 // assets/tiled/map01/tilemap-example-a.tmx
	TilemapExampleB         resources.Asset = 0x9e04cca827d1ffc6 // assets/tiled/map02/tilemap-example-b.tmx
	TilemapCharactersPacked resources.Asset = 0x887669217c4d6120 // assets/tiled/shared/images/tilemap-characters_packed.png
	TilemapPacked           resources.Asset = 0xcb8d155ee372a4af // assets/tiled/shared/images/tilemap_packed.png
	TilesetCharacters       resources.Asset = 0x7e18b3a57e2d5ee7 // assets/tiled/shared/sets/tileset-characters.tsx
	TilesetTiles            resources.Asset = 0x5a8c9444088a8942 // assets/tiled/shared/sets/tileset-tiles.tsx
	Splash1920x1080Black    resources.Asset = 0x783414191130c7d  // static/Images/splash_1920x1080_black.png
)

// =============== Manifests ===============

var (
	AssetsManifest = resources.AssetManifest{
		0xfca5063c33d5d3f6: "assets/aseprite/characters/characters_data.json",
		0x17d0b26b6cf1aecc: "assets/aseprite/characters/characters_img.png",
		0x7d30d7ac63574117: "assets/tiled/map01/tilemap-example-a.tmx",
		0x9e04cca827d1ffc6: "assets/tiled/map02/tilemap-example-b.tmx",
		0x887669217c4d6120: "assets/tiled/shared/images/tilemap-characters_packed.png",
		0xcb8d155ee372a4af: "assets/tiled/shared/images/tilemap_packed.png",
		0x7e18b3a57e2d5ee7: "assets/tiled/shared/sets/tileset-characters.tsx",
		0x5a8c9444088a8942: "assets/tiled/shared/sets/tileset-tiles.tsx",
	}
	StaticManifest = resources.AssetManifest{
		0x783414191130c7d: "static/Images/splash_1920x1080_black.png",
	}
)

// =============== Resource Systems ===============

var (
	Assets = resources.NewResourceSystem("assets", AssetsManifest,
		resources.ResourceSystemOptions{
			TrimRoot: true,
		},
	)
	Static = resources.NewResourceSystem("static", StaticManifest,
		resources.ResourceSystemOptions{
			TrimRoot: false,
		},
	)
)

// =============== Initialization ===============

func init() {
	Static.UseFilesystem(staticEmbeddedFS)
}
