package manifest

import (
	"regexp"
	"strings"
	"text/template"
	"unicode"
)

var nonAlnum = regexp.MustCompile(`[^A-Za-z0-9]+`)

const templateContent = `
// Code generated by flinch-cli. DO NOT EDIT.
package {{ .Package }}

import (
	"embed"
	"github.com/adm87/flinch/engine/resources"
)

// =============== Embedded Directories ===============
{{ range .Directories }}
{{ if .IsEmbedded }}
//go:embed {{ .Path }}
var {{ toIdentifier .Name | camel }}EmbeddedFS embed.FS
{{ end }}
{{ end }}

// =============== Assets ===============

const (
{{- range .Directories }}
	{{- range .Files }}
	{{ toIdentifier .Name }} resources.Asset = {{ .Hash }} // {{ .Path }}
	{{- end }}
{{- end }}
)

// =============== Manifests ===============

var (
{{- range .Directories }}
	{{ toIdentifier .Name }}Manifest = resources.AssetManifest{
	{{- range .Files }}
		{{ .Hash }}: "{{ .Path }}",
	{{- end }}
	}
{{- end }}
)

// =============== Resource Systems ===============

var (
{{- range .Directories }}
	{{ toIdentifier .Name }} = resources.NewResourceSystem("{{ .Name }}", {{ toIdentifier .Name }}Manifest, 
		resources.ResourceSystemOptions{
			TrimRoot: {{ not .IsEmbedded }},
		},
	)
{{- end }}
)

// =============== Initialization ===============

func init() {
{{- range .Directories }}
	{{- if .IsEmbedded }}
	{{ toIdentifier .Name }}.SetFileSystem({{ toIdentifier .Name | camel }}EmbeddedFS)
	{{- end }}
{{- end }}
}
`

func GenerateFromTemplate(model *Model) (string, error) {
	tmpl, err := template.New("manifest").
		Funcs(template.FuncMap{
			"camel":        camel,
			"toIdentifier": toIdentifier,
		}).Parse(templateContent)

	if err != nil {
		return "", err
	}

	sb := &strings.Builder{}

	if err := tmpl.Execute(sb, model); err != nil {
		return "", err
	}

	return sb.String(), nil
}

func camel(s string) string {
	if len(s) == 0 {
		return s
	}
	runes := []rune(s)
	runes[0] = []rune(string(runes[0]))[0] | 0x20
	return string(runes)
}

func toIdentifier(s string) string {
	// Replace separators with spaces
	cleaned := nonAlnum.ReplaceAllString(s, " ")
	parts := strings.Fields(cleaned)

	if len(parts) == 0 {
		return "_"
	}

	// PascalCase
	for i, p := range parts {
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		parts[i] = string(r)
	}

	id := strings.Join(parts, "")

	// If it starts with a digit, prefix underscore
	if unicode.IsDigit([]rune(id)[0]) {
		id = "_" + id
	}

	return id
}
