// Code generated by flinch-cli. DO NOT EDIT.
package data

import (
	"embed"
	"github.com/adm87/flinch/engine/resources"
)

// =============== Embedded Directories ===============

//go:embed static
var staticEmbeddedFS embed.FS

// =============== Assets ===============

const (
	Tile0000 resources.Asset = 0xe73294f7767bf8c3 // static/tile_0000.png
	Tile0001 resources.Asset = 0x47ad4014ede46f30 // static/tile_0001.png
	Tile0002 resources.Asset = 0xfcef9f9e99de589  // static/tile_0002.png
	Tile0003 resources.Asset = 0xc515a3044680f116 // static/tile_0003.png
	Tile0004 resources.Asset = 0xb44162205dcf800f // static/tile_0004.png
	Tile0005 resources.Asset = 0x69890b2abab43e9c // static/tile_0005.png
	Tile0006 resources.Asset = 0xaf56c616ccfaa1d5 // static/tile_0006.png
	Tile0007 resources.Asset = 0x67976f212c65b782 // static/tile_0007.png
	Tile0008 resources.Asset = 0x38062dc560ca4cbb // static/tile_0008.png
	Tile0009 resources.Asset = 0xed4cd6cfbdad5848 // static/tile_0009.png
	Tile0010 resources.Asset = 0x44cbc7f40e00576a // static/tile_0010.png
	Tile0011 resources.Asset = 0x797afee913628c7d // static/tile_0011.png
	Tile0012 resources.Asset = 0xc7636504b563d584 // static/tile_0012.png
	Tile0013 resources.Asset = 0x7b009af2a155f4b7 // static/tile_0013.png
	Tile0014 resources.Asset = 0x22effcde413087fe // static/tile_0014.png
	Tile0015 resources.Asset = 0xbef255ebe3ee6951 // static/tile_0015.png
	Tile0016 resources.Asset = 0x24e198e7cf7f0f18 // static/tile_0016.png
	Tile0017 resources.Asset = 0xc3f9edca57b9c6cb // static/tile_0017.png
	Tile0018 resources.Asset = 0x9f2c31393e376e52 // static/tile_0018.png
	Tile0019 resources.Asset = 0x3dd7861bc6155425 // static/tile_0019.png
	Tile0020 resources.Asset = 0xee4f9d68726642f5 // static/tile_0020.png
	Tile0021 resources.Asset = 0xf9af466de6ef84a2 // static/tile_0021.png
	Tile0022 resources.Asset = 0x49033541fd7b04af // static/tile_0022.png
	Tile0023 resources.Asset = 0xfe4ade4c5a5fc33c // static/tile_0023.png
	Tile0024 resources.Asset = 0xa1e6d146a427b2a9 // static/tile_0024.png
	Tile0025 resources.Asset = 0x572e7a51010c7136 // static/tile_0025.png
	Tile0026 resources.Asset = 0x794a6c443105c5e3 // static/tile_0026.png
	Tile0027 resources.Asset = 0xdc7013368d91a6d0 // static/tile_0027.png
	Tile0028 resources.Asset = 0xd3ff141dbc1c55cd // static/tile_0028.png
	Tile0029 resources.Asset = 0xf469df40b997a27a // static/tile_0029.png
	Tile0030 resources.Asset = 0xde6e0b25c47c488c // static/tile_0030.png
	Tile0031 resources.Asset = 0x7d8660084cb7003f // static/tile_0031.png
	Tile0032 resources.Asset = 0x85f76f211e2c6c72 // static/tile_0032.png
	Tile0033 resources.Asset = 0x787dc829d8e9efc5 // static/tile_0033.png
	Tile0034 resources.Asset = 0x10f23dfcdccbef60 // static/tile_0034.png
	Tile0035 resources.Asset = 0x5b3e94f27f8c11f3 // static/tile_0035.png
	Tile0036 resources.Asset = 0x3921a2ff4f910a46 // static/tile_0036.png
	Tile0037 resources.Asset = 0xd58ffc0cf2aa0a79 // static/tile_0037.png
	Tile0038 resources.Asset = 0x4b3a2e7ad5a28a4  // static/tile_0038.png
	Tile0039 resources.Asset = 0xb850d8d5994c47d7 // static/tile_0039.png
	Tile0040 resources.Asset = 0xd92538316fbf49bf // static/tile_0040.png
	Tile0041 resources.Asset = 0x3a0ce34ee784920c // static/tile_0041.png
	Tile0042 resources.Asset = 0xd41ca052fbf23945 // static/tile_0042.png
	Tile0043 resources.Asset = 0xe196474a4134b5f2 // static/tile_0043.png
	Tile0044 resources.Asset = 0xb6dd6d1ba2945b73 // static/tile_0044.png
	Tile0045 resources.Asset = 0x6c911625ffd438e0 // static/tile_0045.png
	Tile0046 resources.Asset = 0x312ed43615b253f9 // static/tile_0046.png
	Tile0047 resources.Asset = 0x94c07b28729953c6 // static/tile_0047.png
	Tile0048 resources.Asset = 0x13efb0febc549157 // static/tile_0048.png
	Tile0049 resources.Asset = 0x60527b10d0627224 // static/tile_0049.png
	Tile0050 resources.Asset = 0x20b47b2d69893a96 // static/tile_0050.png
	Tile0051 resources.Asset = 0x6b6dd2230ca62f09 // static/tile_0051.png
	Tile0052 resources.Asset = 0xa34c183e10ecb8b0 // static/tile_0052.png
	Tile0053 resources.Asset = 0x42d16d2099844243 // static/tile_0053.png
	Tile0054 resources.Asset = 0xc336474a4f6e0102 // static/tile_0054.png
	Tile0055 resources.Asset = 0xaf59e3ff002eb55  // static/tile_0055.png
	Tile0056 resources.Asset = 0xc527e353ddbc881c // static/tile_0056.png
	Tile0057 resources.Asset = 0xfe03a4980d7c98f  // static/tile_0057.png
	Tile0058 resources.Asset = 0x4450171a6d45632e // static/tile_0058.png
	Tile0059 resources.Asset = 0x38f16e14f8bdd481 // static/tile_0059.png
	Tile0060 resources.Asset = 0xf5ca53d8d7fd6861 // static/tile_0060.png
	Tile0061 resources.Asset = 0xae0afce337687e0e // static/tile_0061.png
	Tile0062 resources.Asset = 0xfab5efe268d3f99b // static/tile_0062.png
	Tile0063 resources.Asset = 0x68198e7ddb85a28  // static/tile_0063.png
	Tile0064 resources.Asset = 0x495feee099a828d  // static/tile_0064.png
	Tile0065 resources.Asset = 0x7b86ca0c1f18d73a // static/tile_0065.png
	Tile0066 resources.Asset = 0x5d799af2b0473087 // static/tile_0066.png
	Tile0067 resources.Asset = 0x53576509ac53bc54 // static/tile_0067.png
	Tile0068 resources.Asset = 0xcf18bc16eec46969 // static/tile_0068.png
	Tile0069 resources.Asset = 0x87c565214e8a9df6 // static/tile_0069.png
	Tile0070 resources.Asset = 0x92c9c19b14f541f8 // static/tile_0070.png
	Tile0071 resources.Asset = 0x85bd1aa3d00f972b // static/tile_0071.png
	Tile0072 resources.Asset = 0x8e2e29bca185035e // static/tile_0072.png
	Tile0073 resources.Asset = 0x2cd97e9f2962e931 // static/tile_0073.png
	Tile0074 resources.Asset = 0x354a8db7fad85564 // static/tile_0074.png
	Tile0075 resources.Asset = 0x3f6cc3a0fecbc997 // static/tile_0075.png
	Tile0076 resources.Asset = 0xb008f4d26e531fca // static/tile_0076.png
	Tile0077 resources.Asset = 0xe1532bc770d3dedd // static/tile_0077.png
	Tile0078 resources.Asset = 0x980f28c8424d2420 // static/tile_0078.png
	Tile0079 resources.Asset = 0x886f7fc2ca2715b3 // static/tile_0079.png
	Tile0080 resources.Asset = 0xe15bf2ccf317e0ab // static/tile_0080.png
	Tile0081 resources.Asset = 0xee6899c437fd8b78 // static/tile_0081.png
	Tile0082 resources.Asset = 0x887856c84c6b32b1 // static/tile_0082.png
	Tile0083 resources.Asset = 0xe9cd01e5c48d4cde // static/tile_0083.png
	Tile0084 resources.Asset = 0x9b0b9bca21d41317 // static/tile_0084.png
	Tile0085 resources.Asset = 0x90e965e11de09ee4 // static/tile_0085.png
	Tile0086 resources.Asset = 0x3cf203f093dc285d // static/tile_0086.png
	Tile0087 resources.Asset = 0xba7ccfb915b694a  // static/tile_0087.png
	Tile0088 resources.Asset = 0xe40e57ebed2f5f33 // static/tile_0088.png
	Tile0089 resources.Asset = 0xf3ae00f165556da0 // static/tile_0089.png
	Tile0090 resources.Asset = 0x3d351f73643cff72 // static/tile_0090.png
	Tile0091 resources.Asset = 0x2fbb787c1efa82c5 // static/tile_0091.png
	Tile0092 resources.Asset = 0x95abbb780a8cdb8c // static/tile_0092.png
	Tile0093 resources.Asset = 0x34c4105a92c7933f // static/tile_0093.png
	Tile0094 resources.Asset = 0xf05f535195a19d46 // static/tile_0094.png
	Tile0095 resources.Asset = 0x8ccdac5f38ba9d79 // static/tile_0095.png
	Tile0096 resources.Asset = 0xc82fee4f22dc8260 // static/tile_0096.png
	Tile0097 resources.Asset = 0x127c4544c59ca4f3 // static/tile_0097.png
	Tile0098 resources.Asset = 0x36afba5466e5860a // static/tile_0098.png
	Tile0099 resources.Asset = 0x14daf14e5448191d // static/tile_0099.png
	Tile0100 resources.Asset = 0xd345dc3965ef34c8 // static/tile_0100.png
	Tile0101 resources.Asset = 0x1dff332f090c293b // static/tile_0101.png
	Tile0102 resources.Asset = 0xceaa445af27ef62e // static/tile_0102.png
	Tile0103 resources.Asset = 0xc34b9b557df76781 // static/tile_0103.png
	Tile0104 resources.Asset = 0x76a0a8564c8bebf4 // static/tile_0104.png
	Tile0105 resources.Asset = 0x2a3dde44387e0b27 // static/tile_0105.png
	Tile0106 resources.Asset = 0x9ed00d58bf5106da // static/tile_0106.png
	Tile0107 resources.Asset = 0x25354665c4b0faad // static/tile_0107.png
	Tile0108 resources.Asset = 0x2da6457e96264bb0 // static/tile_0108.png
	Tile0109 resources.Asset = 0xcd2b9a611ebdd543 // static/tile_0109.png
	Tile0110 resources.Asset = 0xe23b9938842698f1 // static/tile_0110.png
	Tile0111 resources.Asset = 0xed0b445ae4475e1e // static/tile_0111.png
	Tile0112 resources.Asset = 0xe49a354212d1f1eb // static/tile_0112.png
	Tile0113 resources.Asset = 0x482bdc346fb8f1b8 // static/tile_0113.png
	Tile0114 resources.Asset = 0x43964665b679629d // static/tile_0114.png
	Tile0115 resources.Asset = 0x656b0f6bc916cf8a // static/tile_0115.png
	Tile0116 resources.Asset = 0x9e49de3f418e2457 // static/tile_0116.png
	Tile0117 resources.Asset = 0xeaaca851559c0524 // static/tile_0117.png
	Tile0118 resources.Asset = 0xbb8901769aebe6f9 // static/tile_0118.png
	Tile0119 resources.Asset = 0x1f1aa868f7d2e6c6 // static/tile_0119.png
	Tile0120 resources.Asset = 0xb64c57e3bd63a866 // static/tile_0120.png
	Tile0121 resources.Asset = 0xabe9acc15d9fb519 // static/tile_0121.png
	Tile0122 resources.Asset = 0xe807f2dc65830b80 // static/tile_0122.png
	Tile0123 resources.Asset = 0x2eee49d205600513 // static/tile_0123.png
	Tile0124 resources.Asset = 0x59a72400a4005f92 // static/tile_0124.png
	Tile0125 resources.Asset = 0xf85278e32bde4565 // static/tile_0125.png
	Tile0126 resources.Asset = 0xb4c7bbda2f71f32c // static/tile_0126.png
	Tile0127 resources.Asset = 0x513614e7d28af35f // static/tile_0127.png
	Tile0128 resources.Asset = 0xdd6befa5a6fb2c3e // static/tile_0128.png
	Tile0129 resources.Asset = 0x796d48b349b75a91 // static/tile_0129.png
	Tile0130 resources.Asset = 0xc54254e2db9b794f // static/tile_0130.png
	Tile0131 resources.Asset = 0x7deefded3b61addc // static/tile_0131.png
	Tile0132 resources.Asset = 0x6d37b8de35a6bc15 // static/tile_0132.png
	Tile0133 resources.Asset = 0x257861e89511d1c2 // static/tile_0133.png
	Tile0134 resources.Asset = 0xf83387b9f447f203 // static/tile_0134.png
	Tile0135 resources.Asset = 0x58f32dc56923c70  // static/tile_0135.png
	Tile0136 resources.Asset = 0xca49ecc14f66d6c9 // static/tile_0136.png
	Tile0137 resources.Asset = 0xd97c95c6c7301356 // static/tile_0137.png
	Tile0138 resources.Asset = 0x58abcb9d10eb50e7 // static/tile_0138.png
	Tile0139 resources.Asset = 0xa50e95af24f931b4 // static/tile_0139.png
	Tile0140 resources.Asset = 0x225025c41859645c // static/tile_0140.png
	Tile0141 resources.Asset = 0x69a37cb9b8932fcf // static/tile_0141.png
	Tile0142 resources.Asset = 0xc9d989bf72098842 // static/tile_0142.png
	Tile0143 resources.Asset = 0x1198e0b5129e7295 // static/tile_0143.png
	Tile0144 resources.Asset = 0xa9f05ab33389f2f0 // static/tile_0144.png
	Tile0145 resources.Asset = 0x9c94af90d13fa883 // static/tile_0145.png
	Tile0146 resources.Asset = 0x7dddbd9da427c9d6 // static/tile_0146.png
	Tile0147 resources.Asset = 0x6eab14982c5e8d49 // static/tile_0147.png
	Tile0148 resources.Asset = 0x496fbd8601f0e834 // static/tile_0148.png
	Tile0149 resources.Asset = 0xfd0cf373ede30767 // static/tile_0149.png
	Tile0150 resources.Asset = 0xd75ae2c81bac4a85 // static/tile_0150.png
	Tile0151 resources.Asset = 0x3b5889ba78ee6932 // static/tile_0151.png
	Tile0152 resources.Asset = 0x32e77aa1a778fcff // static/tile_0152.png
	Tile0153 resources.Asset = 0x93cf25bf1f3e454c // static/tile_0153.png
	Tile0154 resources.Asset = 0x37d316ab384f8e39 // static/tile_0154.png
	Tile0155 resources.Asset = 0x9b64bd9d95368e06 // static/tile_0155.png
	Tile0156 resources.Asset = 0xba1aaf90c24cb9b3 // static/tile_0156.png
	Tile0157 resources.Asset = 0xc9ba58963a72c820 // static/tile_0157.png
	Tile0158 resources.Asset = 0x12fe5b9568f982dd // static/tile_0158.png
	Tile0159 resources.Asset = 0xe1b424a06678c3ca // static/tile_0159.png
	Tile0160 resources.Asset = 0xda62e4aa61d97efa // static/tile_0160.png
	Tile0161 resources.Asset = 0xb9f81987645e324d // static/tile_0161.png
	Tile0162 resources.Asset = 0x8b87fa30715b914  // static/tile_0162.png
	Tile0163 resources.Asset = 0xbc55b590f307d847 // static/tile_0163.png
	Tile0164 resources.Asset = 0x104e17817d0e01ce // static/tile_0164.png
	Tile0165 resources.Asset = 0x580d6e771da2ec21 // static/tile_0165.png
	Tile0166 resources.Asset = 0x68c4b386235ddde8 // static/tile_0166.png
	Tile0167 resources.Asset = 0xb0170a7bc395f65b // static/tile_0167.png
	Tile0168 resources.Asset = 0xdfa84bd78f316122 // static/tile_0168.png
	Tile0169 resources.Asset = 0xd448a2d21aa81f75 // static/tile_0169.png
	Tile0170 resources.Asset = 0xd34f71a8e257bb93 // static/tile_0170.png
	Tile0171 resources.Asset = 0x8c691ab3427ac200 // static/tile_0171.png
	Tile0172 resources.Asset = 0x504ad4983a976b99 // static/tile_0172.png
	Tile0173 resources.Asset = 0x5aad7fba9a5b5ee6 // static/tile_0173.png
	Tile0174 resources.Asset = 0xf5973cbeaf82a9df // static/tile_0174.png
	Tile0175 resources.Asset = 0x5928e3b10c69a9ac // static/tile_0175.png
	Tile0176 resources.Asset = 0x9cb3a0ba08d5fbe5 // static/tile_0176.png
	Tile0177 resources.Asset = 0xfe084bd780f81612 // static/tile_0177.png
	Tile0178 resources.Asset = 0x795c0863b27d768b // static/tile_0178.png
	Tile0179 resources.Asset = 0xda43b3812a42bed8 // static/tile_0179.png
)

// =============== Manifests ===============

var (
	StaticManifest = resources.AssetManifest{
		0xe73294f7767bf8c3: "static/tile_0000.png",
		0x47ad4014ede46f30: "static/tile_0001.png",
		0xfcef9f9e99de589:  "static/tile_0002.png",
		0xc515a3044680f116: "static/tile_0003.png",
		0xb44162205dcf800f: "static/tile_0004.png",
		0x69890b2abab43e9c: "static/tile_0005.png",
		0xaf56c616ccfaa1d5: "static/tile_0006.png",
		0x67976f212c65b782: "static/tile_0007.png",
		0x38062dc560ca4cbb: "static/tile_0008.png",
		0xed4cd6cfbdad5848: "static/tile_0009.png",
		0x44cbc7f40e00576a: "static/tile_0010.png",
		0x797afee913628c7d: "static/tile_0011.png",
		0xc7636504b563d584: "static/tile_0012.png",
		0x7b009af2a155f4b7: "static/tile_0013.png",
		0x22effcde413087fe: "static/tile_0014.png",
		0xbef255ebe3ee6951: "static/tile_0015.png",
		0x24e198e7cf7f0f18: "static/tile_0016.png",
		0xc3f9edca57b9c6cb: "static/tile_0017.png",
		0x9f2c31393e376e52: "static/tile_0018.png",
		0x3dd7861bc6155425: "static/tile_0019.png",
		0xee4f9d68726642f5: "static/tile_0020.png",
		0xf9af466de6ef84a2: "static/tile_0021.png",
		0x49033541fd7b04af: "static/tile_0022.png",
		0xfe4ade4c5a5fc33c: "static/tile_0023.png",
		0xa1e6d146a427b2a9: "static/tile_0024.png",
		0x572e7a51010c7136: "static/tile_0025.png",
		0x794a6c443105c5e3: "static/tile_0026.png",
		0xdc7013368d91a6d0: "static/tile_0027.png",
		0xd3ff141dbc1c55cd: "static/tile_0028.png",
		0xf469df40b997a27a: "static/tile_0029.png",
		0xde6e0b25c47c488c: "static/tile_0030.png",
		0x7d8660084cb7003f: "static/tile_0031.png",
		0x85f76f211e2c6c72: "static/tile_0032.png",
		0x787dc829d8e9efc5: "static/tile_0033.png",
		0x10f23dfcdccbef60: "static/tile_0034.png",
		0x5b3e94f27f8c11f3: "static/tile_0035.png",
		0x3921a2ff4f910a46: "static/tile_0036.png",
		0xd58ffc0cf2aa0a79: "static/tile_0037.png",
		0x4b3a2e7ad5a28a4:  "static/tile_0038.png",
		0xb850d8d5994c47d7: "static/tile_0039.png",
		0xd92538316fbf49bf: "static/tile_0040.png",
		0x3a0ce34ee784920c: "static/tile_0041.png",
		0xd41ca052fbf23945: "static/tile_0042.png",
		0xe196474a4134b5f2: "static/tile_0043.png",
		0xb6dd6d1ba2945b73: "static/tile_0044.png",
		0x6c911625ffd438e0: "static/tile_0045.png",
		0x312ed43615b253f9: "static/tile_0046.png",
		0x94c07b28729953c6: "static/tile_0047.png",
		0x13efb0febc549157: "static/tile_0048.png",
		0x60527b10d0627224: "static/tile_0049.png",
		0x20b47b2d69893a96: "static/tile_0050.png",
		0x6b6dd2230ca62f09: "static/tile_0051.png",
		0xa34c183e10ecb8b0: "static/tile_0052.png",
		0x42d16d2099844243: "static/tile_0053.png",
		0xc336474a4f6e0102: "static/tile_0054.png",
		0xaf59e3ff002eb55:  "static/tile_0055.png",
		0xc527e353ddbc881c: "static/tile_0056.png",
		0xfe03a4980d7c98f:  "static/tile_0057.png",
		0x4450171a6d45632e: "static/tile_0058.png",
		0x38f16e14f8bdd481: "static/tile_0059.png",
		0xf5ca53d8d7fd6861: "static/tile_0060.png",
		0xae0afce337687e0e: "static/tile_0061.png",
		0xfab5efe268d3f99b: "static/tile_0062.png",
		0x68198e7ddb85a28:  "static/tile_0063.png",
		0x495feee099a828d:  "static/tile_0064.png",
		0x7b86ca0c1f18d73a: "static/tile_0065.png",
		0x5d799af2b0473087: "static/tile_0066.png",
		0x53576509ac53bc54: "static/tile_0067.png",
		0xcf18bc16eec46969: "static/tile_0068.png",
		0x87c565214e8a9df6: "static/tile_0069.png",
		0x92c9c19b14f541f8: "static/tile_0070.png",
		0x85bd1aa3d00f972b: "static/tile_0071.png",
		0x8e2e29bca185035e: "static/tile_0072.png",
		0x2cd97e9f2962e931: "static/tile_0073.png",
		0x354a8db7fad85564: "static/tile_0074.png",
		0x3f6cc3a0fecbc997: "static/tile_0075.png",
		0xb008f4d26e531fca: "static/tile_0076.png",
		0xe1532bc770d3dedd: "static/tile_0077.png",
		0x980f28c8424d2420: "static/tile_0078.png",
		0x886f7fc2ca2715b3: "static/tile_0079.png",
		0xe15bf2ccf317e0ab: "static/tile_0080.png",
		0xee6899c437fd8b78: "static/tile_0081.png",
		0x887856c84c6b32b1: "static/tile_0082.png",
		0xe9cd01e5c48d4cde: "static/tile_0083.png",
		0x9b0b9bca21d41317: "static/tile_0084.png",
		0x90e965e11de09ee4: "static/tile_0085.png",
		0x3cf203f093dc285d: "static/tile_0086.png",
		0xba7ccfb915b694a:  "static/tile_0087.png",
		0xe40e57ebed2f5f33: "static/tile_0088.png",
		0xf3ae00f165556da0: "static/tile_0089.png",
		0x3d351f73643cff72: "static/tile_0090.png",
		0x2fbb787c1efa82c5: "static/tile_0091.png",
		0x95abbb780a8cdb8c: "static/tile_0092.png",
		0x34c4105a92c7933f: "static/tile_0093.png",
		0xf05f535195a19d46: "static/tile_0094.png",
		0x8ccdac5f38ba9d79: "static/tile_0095.png",
		0xc82fee4f22dc8260: "static/tile_0096.png",
		0x127c4544c59ca4f3: "static/tile_0097.png",
		0x36afba5466e5860a: "static/tile_0098.png",
		0x14daf14e5448191d: "static/tile_0099.png",
		0xd345dc3965ef34c8: "static/tile_0100.png",
		0x1dff332f090c293b: "static/tile_0101.png",
		0xceaa445af27ef62e: "static/tile_0102.png",
		0xc34b9b557df76781: "static/tile_0103.png",
		0x76a0a8564c8bebf4: "static/tile_0104.png",
		0x2a3dde44387e0b27: "static/tile_0105.png",
		0x9ed00d58bf5106da: "static/tile_0106.png",
		0x25354665c4b0faad: "static/tile_0107.png",
		0x2da6457e96264bb0: "static/tile_0108.png",
		0xcd2b9a611ebdd543: "static/tile_0109.png",
		0xe23b9938842698f1: "static/tile_0110.png",
		0xed0b445ae4475e1e: "static/tile_0111.png",
		0xe49a354212d1f1eb: "static/tile_0112.png",
		0x482bdc346fb8f1b8: "static/tile_0113.png",
		0x43964665b679629d: "static/tile_0114.png",
		0x656b0f6bc916cf8a: "static/tile_0115.png",
		0x9e49de3f418e2457: "static/tile_0116.png",
		0xeaaca851559c0524: "static/tile_0117.png",
		0xbb8901769aebe6f9: "static/tile_0118.png",
		0x1f1aa868f7d2e6c6: "static/tile_0119.png",
		0xb64c57e3bd63a866: "static/tile_0120.png",
		0xabe9acc15d9fb519: "static/tile_0121.png",
		0xe807f2dc65830b80: "static/tile_0122.png",
		0x2eee49d205600513: "static/tile_0123.png",
		0x59a72400a4005f92: "static/tile_0124.png",
		0xf85278e32bde4565: "static/tile_0125.png",
		0xb4c7bbda2f71f32c: "static/tile_0126.png",
		0x513614e7d28af35f: "static/tile_0127.png",
		0xdd6befa5a6fb2c3e: "static/tile_0128.png",
		0x796d48b349b75a91: "static/tile_0129.png",
		0xc54254e2db9b794f: "static/tile_0130.png",
		0x7deefded3b61addc: "static/tile_0131.png",
		0x6d37b8de35a6bc15: "static/tile_0132.png",
		0x257861e89511d1c2: "static/tile_0133.png",
		0xf83387b9f447f203: "static/tile_0134.png",
		0x58f32dc56923c70:  "static/tile_0135.png",
		0xca49ecc14f66d6c9: "static/tile_0136.png",
		0xd97c95c6c7301356: "static/tile_0137.png",
		0x58abcb9d10eb50e7: "static/tile_0138.png",
		0xa50e95af24f931b4: "static/tile_0139.png",
		0x225025c41859645c: "static/tile_0140.png",
		0x69a37cb9b8932fcf: "static/tile_0141.png",
		0xc9d989bf72098842: "static/tile_0142.png",
		0x1198e0b5129e7295: "static/tile_0143.png",
		0xa9f05ab33389f2f0: "static/tile_0144.png",
		0x9c94af90d13fa883: "static/tile_0145.png",
		0x7dddbd9da427c9d6: "static/tile_0146.png",
		0x6eab14982c5e8d49: "static/tile_0147.png",
		0x496fbd8601f0e834: "static/tile_0148.png",
		0xfd0cf373ede30767: "static/tile_0149.png",
		0xd75ae2c81bac4a85: "static/tile_0150.png",
		0x3b5889ba78ee6932: "static/tile_0151.png",
		0x32e77aa1a778fcff: "static/tile_0152.png",
		0x93cf25bf1f3e454c: "static/tile_0153.png",
		0x37d316ab384f8e39: "static/tile_0154.png",
		0x9b64bd9d95368e06: "static/tile_0155.png",
		0xba1aaf90c24cb9b3: "static/tile_0156.png",
		0xc9ba58963a72c820: "static/tile_0157.png",
		0x12fe5b9568f982dd: "static/tile_0158.png",
		0xe1b424a06678c3ca: "static/tile_0159.png",
		0xda62e4aa61d97efa: "static/tile_0160.png",
		0xb9f81987645e324d: "static/tile_0161.png",
		0x8b87fa30715b914:  "static/tile_0162.png",
		0xbc55b590f307d847: "static/tile_0163.png",
		0x104e17817d0e01ce: "static/tile_0164.png",
		0x580d6e771da2ec21: "static/tile_0165.png",
		0x68c4b386235ddde8: "static/tile_0166.png",
		0xb0170a7bc395f65b: "static/tile_0167.png",
		0xdfa84bd78f316122: "static/tile_0168.png",
		0xd448a2d21aa81f75: "static/tile_0169.png",
		0xd34f71a8e257bb93: "static/tile_0170.png",
		0x8c691ab3427ac200: "static/tile_0171.png",
		0x504ad4983a976b99: "static/tile_0172.png",
		0x5aad7fba9a5b5ee6: "static/tile_0173.png",
		0xf5973cbeaf82a9df: "static/tile_0174.png",
		0x5928e3b10c69a9ac: "static/tile_0175.png",
		0x9cb3a0ba08d5fbe5: "static/tile_0176.png",
		0xfe084bd780f81612: "static/tile_0177.png",
		0x795c0863b27d768b: "static/tile_0178.png",
		0xda43b3812a42bed8: "static/tile_0179.png",
	}
)

// =============== Resource Systems ===============

var (
	Static = resources.NewResourceSystem("static", StaticManifest,
		resources.ResourceSystemOptions{
			TrimRoot: false,
		},
	)
)

// =============== Initialization ===============

func init() {
	Static.UseFilesystem(staticEmbeddedFS)
}
